version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./bot:/data/bot
    command: python bot.py
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: on-failure
    volumes:
      - ./mongo_data:/data/mongo
    ports:
      - "27017:27017"

volumes:
  mongo_data:
  bot: